category:
    resource: '@AppBundle/Controller/CategoryController.php'
    prefix: /api
    type: rest

product:
    resource: '@AppBundle/Controller/ProduitController.php'
    prefix: /api
    type: rest